_BASE_: Base-bagtricks.yml # 上一级配置文件

MODEL:
  BACKBONE:
    WITH_NL: True # 模型是否使用 NO-LOCAL module

  HEADS:
    POOL_LAYER: gempool # HEADS POOL_LAYER

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss") # LOSS FUNCTION
    CE:
      EPSILON: 0.1
      SCALE: 1.0

    TRI:
      MARGIN: 0.0
      HARD_MINING: False
      SCALE: 1.0
